name: Publish dislocs to PyPI

on:
  release:
    types: [published]  # triggered when you issue a GitHub Release 

jobs:
  build-and-publish:
    runs-on: macos-latest
    permissions:
      id-token: write
    environment: pypi  # the environment name of PyPI configuration

    steps:
      # checkout codes
      - uses: actions/checkout@v4

      # configure python environment
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - name: Install system dependencies
        run: |
          brew install cmake

      # install the build tool
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "scikit-build-core>=0.4.0" cmake "numpy>=2.0.0" build

      # building wheel and sdist
      - name: Build wheel and sdist
        run: |
          python -m build --wheel --sdist --outdir dist

      # upload-artifact to GitHub Artifacts (optional, for debuging)
      - uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist/*

      # upload to pypi
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://upload.pypi.org/legacy/
